# Site settings
title: Eva Garcia Martin
description: 'Data Scientist | Machine Learning Researcher'
url: 'http://egarciamartin.github.io'
baseurl: ''
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'
# disable_landing_page: true

author:
  name: 'Eva Garcia Martin'
  email: eva.g.596@gmail.com
  twitter_username: evitamonal
  github_username:  egarciamartin
  linkedin_username:  evagarciamartin
  # google_scholar:  9LJwmLkAAAAJ&hl=en

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
